import {useEffect,useMemo,useState} from 'react';
import {Plus,GripVertical,Trash2,Copy,Settings2,Eye,Download,Upload,Sparkles,Check,X,BarChart3,ExternalLink} from 'lucide-react';
type Kind='short'|'long'|'email'|'number'|'select'|'radio'|'checkbox'|'date'|'file'|'rating';
type Field={id:string;kind:Kind;label:string;help:string;required:boolean;options:string[];placeholder:string};
const kinds=[['short','Short text','Aa'],['long','Long text','¶'],['email','Email','@'],['number','Number','#'],['select','Dropdown','⌄'],['radio','Choice','◉'],['checkbox','Checks','☑'],['date','Date','◷'],['file','Upload','↥'],['rating','Rating','★']] as [Kind,string,string][];
const starter:Field[]=[{id:'f1',kind:'short',label:'Full name',help:'Tell us who you are.',required:true,options:[],placeholder:'Jane Appleseed'},{id:'f2',kind:'email',label:'Work email',help:'We will send your confirmation here.',required:true,options:[],placeholder:'jane@company.com'},{id:'f3',kind:'select',label:'What can we help with?',help:'Choose the closest match.',required:true,options:['Product demo','Partnership','Support','Something else'],placeholder:'Select an option'}];
const uid=()=>Math.random().toString(36).slice(2,9);
export default function App(){
 const[fields,setFields]=useState(starter),[selected,setSelected]=useState('f1'),[tab,setTab]=useState('content'),[preview,setPreview]=useState(false),[theme,setTheme]=useState('aurora'),[toast,setToast]=useState('');
 const cur=fields.find(f=>f.id===selected)||fields[0], score=Math.min(98,70+fields.length*7), update=(p:Partial<Field>)=>setFields(x=>x.map(f=>f.id===selected?{...f,...p}:f));
 useEffect(()=>{try{const s=localStorage.getItem('formcraft');if(s)setFields(JSON.parse(s))}catch{}},[]);useEffect(()=>localStorage.setItem('formcraft',JSON.stringify(fields)),[fields]);useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2200);return()=>clearTimeout(t)}},[toast]);
 const add=(kind:Kind='short')=>{const f:Field={id:uid(),kind,label:kinds.find(k=>k[0]===kind)?.[1]||'New question',help:'Add a helpful hint for respondents.',required:false,options:['select','radio','checkbox'].includes(kind)?['Option one','Option two']:[],placeholder:''};setFields(x=>[...x,f]);setSelected(f.id)};
 const remove=()=>{if(fields.length<2)return;const i=fields.findIndex(f=>f.id===selected),n=fields[i-1]||fields[i+1];setFields(x=>x.filter(f=>f.id!==selected));setSelected(n.id)};
 const duplicate=()=>{const i=fields.findIndex(f=>f.id===selected),f={...cur,id:uid(),label:cur.label+' copy',options:[...cur.options]};setFields(x=>[...x.slice(0,i+1),f,...x.slice(i+1)]);setSelected(f.id)};
 const exportForm=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({name:'Customer discovery',theme,fields},null,2)],{type:'application/json'}));a.download='formcraft.json';a.click();setToast('Form exported')};
 if(preview)return <div className="preview-mode"><header className="preview-top"><div className="logo-mark">F</div><b>FORMCRAFT</b><button onClick={()=>setPreview(false)}>← Back to builder</button></header><div className={'live-form '+theme}><div className="live-head"><span>CUSTOMER DISCOVERY · FORM 01</span><h1>Let’s build something useful.</h1><p>A few thoughtful questions. No busywork.</p><div className="progress"><i style={{width:score+'%'}}/></div><small>{score}% ready · {fields.length} questions</small></div>{fields.map((f,i)=><div className="live-field" key={f.id}><label>{i+1}. {f.label}{f.required&&<b>*</b>}</label><p>{f.help}</p><Input f={f}/></div>)}<button className="submit">Send response <span>↗</span></button><small className="privacy">Browser-only demo · no response leaves this device.</small></div></div>;
 return <div className={'app '+theme}><header className="nav"><div className="brand"><div className="logo-mark">F</div><div><b>FORMCRAFT</b><small>SMART FORM BUILDER</small></div></div><div className="autosave"><i/> Autosaved just now</div><div className="nav-actions"><button className="icon-btn"><BarChart3 size={18}/></button><button className="outline" onClick={()=>setPreview(true)}><Eye size={17}/> Preview</button><button className="publish" onClick={()=>setToast('Demo published · share link copied')}>Publish <ExternalLink size={15}/></button></div></header>
 <section className="hero"><div><div className="kicker"><Sparkles size={14}/> BUILD / TEST / SHIP</div><h1>Make forms people<br/><em>actually finish.</em></h1><p>Compose polished forms with logic, themes and a live experience.</p></div><div className="score"><span>FORM SCORE</span><strong>{score}</strong><small>/ 100 · excellent</small></div></section>
 <main className="workspace"><aside className="sidebar"><div className="side-title">QUESTION LIBRARY <Plus size={16}/></div>{kinds.map(k=><button className="kind" key={k[0]} onClick={()=>add(k[0])}><i>{k[2]}</i><span>{k[1]}</span><Plus size={14}/></button>)}<div className="tip"><Sparkles size={15}/><b>Smart suggestions</b><p>One clear question per step keeps completion high.</p></div></aside>
 <section className="canvas"><div className="canvas-head"><div><small>UNTITLED PROJECT / FORM 01</small><input defaultValue="Customer discovery"/></div><div className="view-toggle"><button className="active">Builder</button><button onClick={()=>setPreview(true)}>Live view</button></div></div><div className="flow">{fields.map((f,i)=><div className={'node '+(selected===f.id?'selected':'')} key={f.id} onClick={()=>setSelected(f.id)}><div className="node-index">{String(i+1).padStart(2,'0')}</div><GripVertical className="grip" size={16}/><div className="node-copy"><span>{kinds.find(k=>k[0]===f.kind)?.[1].toUpperCase()}</span><strong>{f.label}</strong><small>{f.required?'Required':'Optional'} · {f.help}</small></div><button className="node-menu">•••</button></div>)}<button className="add-step" onClick={()=>add()}><Plus size={18}/> Add question</button></div></section>
 <aside className="inspector"><div className="tabs"><button className={tab==='content'?'active':''} onClick={()=>setTab('content')}>Content</button><button className={tab==='logic'?'active':''} onClick={()=>setTab('logic')}>Logic</button><button className={tab==='style'?'active':''} onClick={()=>setTab('style')}>Style</button></div>{tab==='content'?<><div className="inspect-title"><div><span>QUESTION {String(fields.findIndex(f=>f.id===cur.id)+1).padStart(2,'0')}</span><h2>Edit question</h2></div><button className="danger" onClick={remove}><Trash2 size={16}/></button></div><label>Question<textarea value={cur.label} onChange={e=>update({label:e.target.value})}/></label><label>Helper text<textarea value={cur.help} onChange={e=>update({help:e.target.value})}/></label><label>Placeholder<input value={cur.placeholder} onChange={e=>update({placeholder:e.target.value})}/></label><div className="switch-row"><div><b>Required question</b><small>Respondents must answer this.</small></div><button className={'switch '+(cur.required?'on':'')} onClick={()=>update({required:!cur.required})}><i/></button></div>{cur.options.length>0&&<div className="options"><div className="option-head"><b>Answer choices</b><button onClick={()=>update({options:[...cur.options,'New option']})}><Plus size={14}/> Add</button></div>{cur.options.map((o,i)=><div className="option" key={i}><span>{i+1}</span><input value={o} onChange={e=>update({options:cur.options.map((x,j)=>j===i?e.target.value:x)})}/><button onClick={()=>update({options:cur.options.filter((_,j)=>j!==i)})}><X size={14}/></button></div>)}</div>}<button className="duplicate" onClick={duplicate}><Copy size={15}/> Duplicate question</button></>:tab==='logic'?<Logic fields={fields}/>:<Style theme={theme} setTheme={setTheme}/>}</aside></main>
 <footer className="footer"><div><span>{fields.length} questions</span><span>{fields.filter(f=>f.required).length} required</span><span>Local draft</span></div><div className="footer-actions"><label><Upload size={14}/> Import<input type="file" accept="application/json" hidden onChange={e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(String(r.result));if(Array.isArray(x.fields)){setFields(x.fields);setSelected(x.fields[0].id);setToast('Form imported')}}catch{setToast('Invalid file')}};r.readAsText(f)}}/></label><button onClick={exportForm}><Download size={14}/> Export JSON</button><button onClick={()=>{setFields(starter);setSelected('f1');setToast('Draft reset')}}>Reset</button></div></footer>{toast&&<div className="toast"><Check size={16}/>{toast}</div>}</div>;
}
function Input({f}:{f:Field}){if(f.kind==='long')return <textarea placeholder={f.placeholder}/>;if(f.kind==='select')return <select defaultValue=""><option value="" disabled>{f.placeholder||'Choose…'}</option>{f.options.map(x=><option key={x}>{x}</option>)}</select>;if(['radio','checkbox'].includes(f.kind))return <div className="choices">{f.options.map(x=><label key={x}><input type={f.kind==='radio'?'radio':'checkbox'}/>{x}</label>)}</div>;if(f.kind==='rating')return <div className="stars">☆ ☆ ☆ ☆ ☆</div>;return <input type={f.kind==='email'?'email':f.kind==='number'?'number':f.kind==='date'?'date':'text'} placeholder={f.placeholder}/>}
function Logic({fields}:{fields:Field[]}){return <div className="logic"><div className="logic-icon">⌁</div><h2>Branch the experience</h2><p>Show or skip questions based on answers.</p><div className="rule"><b>IF</b><select><option>{fields[0]?.label}</option></select><select><option>contains</option><option>equals</option></select><input placeholder="value"/></div><div className="rule"><b>THEN</b><select><option>Show question</option><option>Hide question</option></select><select><option>{fields[1]?.label}</option></select></div><button className="duplicate"><Plus size={15}/> Add logic rule</button></div>}
function Style({theme,setTheme}:{theme:string;setTheme:(x:string)=>void}){return <div className="settings"><div className="inspect-title"><div><span>FORM EXPERIENCE</span><h2>Style system</h2></div><Settings2 size={18}/></div><p>Pick a visual language. The live form updates immediately.</p>{[['aurora','Aurora'],['citrus','Citrus'],['violet','Violet']].map(([id,n])=><button className={'theme-choice '+(theme===id?'picked':'')} key={id} onClick={()=>setTheme(id)}><i className={'swatch '+id}/>{n}{theme===id&&<Check size={15}/>}</button>)}<div className="setting-card"><b>Confirmation</b><p>Thanks — your response has been received.</p></div><div className="setting-card"><b>Security</b><p>Browser-only demo. No response leaves this device.</p></div></div>}
